# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
 branches:
   include:
     - '*'  # Trigger on all pushes
 #paths:
  # include:
   #  - '**'  # Trigger on changes to any file




steps:
 - checkout: self


 - script: |
     git config --global credential.helper store
     git config --global user.email "008440894@coyote.csusb.edu"
     git config --global user.name "008440894-FARHAN"
     git clone https://008440894-FARHAN:$(GitHub-PAT)@github.com/SahilFarhan06/Team-3_Rabbit.git Team-3_Rabbit
     cd Fin-tastic_Division
     git config --global user.email "008440894@coyote.csusb.edu"
     git config --global user.name "008440894"
     git remote add azure https://$(Azure-PAT)@dev.azure.com/008442779/_git/Team%203_Rabbit
     git fetch azure --prune  # Fetch all branches from Azure Repo and prune old references
     for branch in $(git branch -r | grep -v HEAD); do  # Iterate over all branches
         branch_name=$(echo $branch | sed 's/.*\///')  # Extract branch name
         git checkout -B $branch_name azure/$branch_name  # Checkout the branch
         git push origin $branch_name  # Push the branch to GitHub
     done
   displayName: 'Sync Azure Repo to GitHub for all branches'

